name: Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup install
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo fmt --all -- --check
      - run: cargo test --all-targets --all-features
